// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "See license",
        "contact": {
            "name": "Alex Walker",
            "url": "@configwizard on Discord"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/object/{containerId}": {
            "post": {
                "description": "Upload object, depending on request content type, defines the upload type. Max upload size 32 MB",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Upload an object",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the container to get the object metadata from",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "publicKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt r, that makes up part of the signature",
                        "name": "X-r",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt s, that makes up part of the signature",
                        "name": "X-s",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPClientError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPServerError"
                        }
                    }
                }
            }
        },
        "/object/{containerId}/": {
            "get": {
                "description": "Returns the IDs of all the objects in the specified container",
                "tags": [
                    "objects"
                ],
                "summary": "Lists all the objects in a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the container to get the object metadata from",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "publicKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt r, that makes up part of the signature",
                        "name": "X-r",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt s, that makes up part of the signature",
                        "name": "X-s",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPClientError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPServerError"
                        }
                    }
                }
            }
        },
        "/object/{containerId}/{objectId}": {
            "get": {
                "description": "Returns the body of the object requested in either binary or JSON format",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Gets the body of an object",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the container to get the object metadata from",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The ID of the object to get the metadata of",
                        "name": "objectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "publicKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt r, that makes up part of the signature",
                        "name": "X-r",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt s, that makes up part of the signature",
                        "name": "X-s",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/objects.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPClientError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPServerError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete object from container (permanent)",
                "tags": [
                    "objects"
                ],
                "summary": "Delete an object",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the container to get the object metadata from",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The ID of the object to get the metadata of",
                        "name": "objectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "publicKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt r, that makes up part of the signature",
                        "name": "X-r",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt s, that makes up part of the signature",
                        "name": "X-s",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPClientError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPServerError"
                        }
                    }
                }
            },
            "head": {
                "description": "Returns the metadata/HEAD of an object in a container",
                "tags": [
                    "objects"
                ],
                "summary": "Get object metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the container to get the object metadata from",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The ID of the object to get the metadata of",
                        "name": "objectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "publicKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt r, that makes up part of the signature",
                        "name": "X-r",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The bigInt s, that makes up part of the signature",
                        "name": "X-s",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {
                            "NEOFS-META": {
                                "type": "string",
                                "description": "The base64 encoded version of the binary bearer token ready for signing"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPClientError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/objects.HTTPServerError"
                        }
                    },
                    "default": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "objects.HTTPClientError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        },
        "objects.HTTPServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 502
                },
                "message": {
                    "type": "string",
                    "example": "status server error"
                }
            }
        },
        "objects.Object": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "content": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:9000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Greenfinch NeoFS RESTful API",
	Description:      "This API serves as a route to communicate with your containers via HTTP/REST. You will need to have created a container already. This script will help you do this.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
